columns_to_combine = {
    "adhd_1": {"file": "qst-post-1_ASR.csv"},
    "aggression_1": {"file": "qst-post-1_RPQ.csv"},
    "aggression_2": {"file": "qst-post-2_RPQ.csv"},
    "aggression_3": {"file": "qst-post-3_RPQ.csv"},
    "alcohol_1": {"file": "qst-pre-1_ALC_AUD.csv"},
    "alcohol_2": {"file": "qst-pre-2_ALC_AUD.csv"},
    "alcohol_3": {"file": "qst-pre-3_ALC_AUD.csv"},
    "anxiety-sensitivity_1": {"file": "qst-post-1_ASI.csv"},
    "autistic-trait_1": {"file": "qst-post-1_ATQ.csv"},
    "big-5_1": {"file": "qst-post-1_BIG.csv"},
    "burnout_1": {"file": "qst-post-1_UBO.csv"},
    "burnout_2": {"file": "qst-post-2_UBO.csv"},
    "burnout_3": {"file": "qst-post-3_UBO.csv"},
    "cantril_1": {"file": "qst-pre-1_CAN.csv"},
    "cantril_2": {"file": "qst-pre-2_CAN.csv"},
    "cantril_3": {"file": "qst-pre-3_CAN.csv"},
    "childhood-trauma_2": {"file": "qst-post-2_CTQ.csv"},
    "cultural-intelligence_3": {"file": "qst-post-3_CIN.csv"},
    "dark-triad_1": {"file": "qst-post-1_DTR.csv"},
    "demographics_advanced_1": {"file": "qst-pre-1_LIS_demographics.csv"},
    "demographics_advanced_2": {"file": "qst-pre-2_LIS_demographics.csv"},
    "demographics_advanced_3": {"file": "qst-pre-3_LIS_demographics.csv"},
    "demographics_age": {"file": "qst-pre_age.csv"},
    "demographics_sex": {"file": "qst-pre_sex.csv"},
    "demographics_education_1": {"file": "qst-pre-1_LIS_education.csv"},
    "demographics_household_1": {"file": "qst-pre-1_LIS_household.csv"},
    "demographics_household_2": {"file": "qst-pre-2_LIS_household.csv"},
    "demographics_household_3": {"file": "qst-pre-3_LIS_household.csv"},
    "demographics_income_1": {"file": "qst-pre-1_LIS_income.csv"},
    "demographics_income_2": {"file": "qst-pre-2_LIS_income.csv"},
    "demographics_income_3": {"file": "qst-pre-3_LIS_income.csv"},
    "depression_1": {"file": "qst-post-1_IDS.csv"},
    "depression_2": {"file": "qst-post-2_IDS.csv"},
    "depression_3": {"file": "qst-post-3_IDS.csv"},
    "dreaming_1": {"file": "qst-pre-1_DRF.csv"},
    "dreaming_2": {"file": "qst-pre-2_DRF.csv"},
    "dreaming_3": {"file": "qst-pre-3_DRF.csv"},
    "eu-membership_1": {"file": "qst-post-1_EMQ.csv"},
    "eu-membership_2": {"file": "qst-post-2_EMQ.csv"},
    "eu-membership_3": {"file": "qst-post-3_EMQ.csv"},
    "emotion-regulation_1": {"file": "qst-post-1_CER.csv"},
    "emotion-regulation_2": {"file": "qst-post-2_CER.csv"},
    "emotion-regulation_3": {"file": "qst-post-3_CER.csv"},
    "exposure-environment_1": {"file": "qst-post-1_TOX.csv"},
    "exposure-environment_2": {"file": "qst-post-2_TOX.csv"},
    "exposure-environment_3": {"file": "qst-post-3_TOX.csv"},
    "financial-literacy_1": {"file": "qst-post-1_FLI.csv"},
    "financial-literacy_2": {"file": "qst-post-2_FLI.csv"},
    "financial-literacy_3": {"file": "qst-post-3_FLI.csv"},
    "gaming_1": {"file": "qst-pre-1_IGD.csv"},
    "gaming_2": {"file": "qst-pre-2_IGD.csv"},
    "gaming_3": {"file": "qst-pre-3_IGD.csv"},
    "greed_3": {"file": "qst-post-3_DGR.csv"},
    "handedness": {"file": "qst-pre_handedness.csv"},
    "hassles-uplifts_1": {"file": "qst-post-1_DHU.csv"},
    "hassles-uplifts_2": {"file": "qst-post-2_DHU.csv"},
    "hassles-uplifts_3": {"file": "qst-post-3_DHU.csv"},
    "health-complaints_1": {"file": "qst-post-1_HEC.csv"},
    "health-complaints_2": {"file": "qst-post-2_HEC.csv"},
    "health-complaints_3": {"file": "qst-post-3_HEC.csv"},
    "impulsiveness_2": {"file": "qst-post-2_BIS.csv"},
    "lab_task_foraging_1": {"file": "lab-1_tsk_foraging.csv"},
    "lab_task_foraging_2": {"file": "lab-2_tsk_foraging.csv"},
    "lab_task_foraging_3": {"file": "lab-3_tsk_foraging.csv"},
    "language_ravens-matrices_finalscores": {"file": "language_ravens-matrices_finalscores.csv"},
    "language_spontaneous-speech_finalscores": {"file": "language_spontaneous-speech_finalscores.csv"},
    "life-events_1": {"file": "qst-post-1_LIE.csv"},
    "life-events_2": {"file": "qst-post-2_LIE.csv"},
    "life-events_3": {"file": "qst-post-3_LIE.csv"},
    "life-satisfaction_1": {"file": "qst-pre-1_SLS.csv"},
    "life-satisfaction_2": {"file": "qst-pre-2_SLS.csv"},
    "life-satisfaction_3": {"file": "qst-pre-3_SLS.csv"},
    "loneliness_1": {"file": "qst-post-1_ULS.csv"},
    "loneliness_2": {"file": "qst-post-2_ULS.csv"},
    "loneliness_3": {"file": "qst-post-3_ULS.csv"},
    "mindfulness_1": {"file": "qst-pre-1_FFM.csv"},
    "mindfulness_2": {"file": "qst-pre-2_FFM.csv"},
    "mindfulness_3": {"file": "qst-pre-3_FFM.csv"},
    "media-multitasking_1": {"file": "qst-pre-1_MMI.csv"},
    "media-multitasking_2": {"file": "qst-pre-2_MMI.csv"},
    "media-multitasking_3": {"file": "qst-pre-3_MMI.csv"},
    "medication_1": {"file": "qst-post-1_OCM.csv"},
    "medication_2": {"file": "qst-post-2_OCM.csv"},
    "medication_3": {"file": "qst-post-3_OCM.csv"},
    "menstrual-cycle_1": {"file": "qst-pre-1_MCY.csv"},
    "menstrual-cycle_2": {"file": "qst-pre-2_MCY.csv"},
    "menstrual-cycle_3": {"file": "qst-pre-3_MCY.csv"},
    "need-to-belong_1": {"file": "qst-post-1_NBS.csv"},
    "need-to-belong_2": {"file": "qst-post-2_NBS.csv"},
    "need-to-belong_3": {"file": "qst-post-3_NBS.csv"},
    "online_task_ambiguity_processed_1": {"file": "online-1_tsk_ambiguity_processed.csv"},
    "online_task_ambiguity_fulldata_1": {"file": "online-1_tsk_ambiguity_fulldata.csv"},
    "online_task_ambiguity_processed_2": {"file": "online-2_tsk_ambiguity_processed.csv"},
    "online_task_ambiguity_fulldata_2": {"file": "online-2_tsk_ambiguity_fulldata.csv"},
    "online_task_ambiguity_processed_3": {"file": "online-3_tsk_ambiguity_processed.csv"},
    "online_task_ambiguity_fulldata_3": {"file": "online-3_tsk_ambiguity_fulldata.csv"},
    "online_task_public-good_processed_1": {"file": "online-1_tsk_public-good_processed.csv"},
    "online_task_public-good_fulldata_1": {"file": "online-1_tsk_public-good_fulldata.csv"},
    "online_task_public-good_processed_2": {"file": "online-2_tsk_public-good_processed.csv"},
    "online_task_public-good_fulldata_2": {"file": "online-2_tsk_public-good_fulldata.csv"},
    "online_task_public-good_processed_3": {"file": "online-3_tsk_public-good_processed.csv"},
    "online_task_public-good_fulldata_3": {"file": "online-3_tsk_public-good_fulldata.csv"},
    "online_task_risk_processed_1": {"file": "online-1_tsk_risk_processed.csv"},
    "online_task_risk_fulldata_1": {"file": "online-1_tsk_risk_fulldata.csv"},
    "online_task_risk_processed_2": {"file": "online-2_tsk_risk_processed.csv"},
    "online_task_risk_fulldata_2": {"file": "online-2_tsk_risk_fulldata.csv"},
    "online_task_risk_processed_3": {"file": "online-3_tsk_risk_processed.csv"},
    "online_task_risk_fulldata_3": {"file": "online-3_tsk_risk_fulldata.csv"},
    "online_task_time_processed_1": {"file": "online-1_tsk_time_processed.csv"},
    "online_task_time_fulldata_1": {"file": "online-1_tsk_time_fulldata.csv"},
    "online_task_time_processed_2": {"file": "online-2_tsk_time_processed.csv"},
    "online_task_time_fulldata_2": {"file": "online-2_tsk_time_fulldata.csv"},
    "online_task_time_processed_3": {"file": "online-3_tsk_time_processed.csv"},
    "online_task_time_fulldata_3": {"file": "online-3_tsk_time_fulldata.csv"},
    "online_task_trust_processed_1": {"file": None, "files": ["online-1_tsk_trust_A_processed.csv", "online-1_tsk_trust_B_processed.csv"], "combine_files": True},
    "online_task_trust_fulldata_1": {"file": None, "files": ["online-1_tsk_trust_A_fulldata.csv", "online-1_tsk_trust_B_fulldata.csv"], "combine_files": True},
    "online_task_trust_processed_2": {"file": None, "files": ["online-2_tsk_trust_A_processed.csv", "online-2_tsk_trust_B_processed.csv"], "combine_files": True},
    "online_task_trust_fulldata_2": {"file": None, "files": ["online-2_tsk_trust_A_fulldata.csv", "online-2_tsk_trust_B_fulldata.csv"], "combine_files": True},
    "online_task_trust_processed_3": {"file": None, "files": ["online-3_tsk_trust_A_processed.csv", "online-3_tsk_trust_B_processed.csv"], "combine_files": True},
    "online_task_trust_fulldata_3": {"file": None, "files": ["online-3_tsk_trust_A_fulldata.csv", "online-3_tsk_trust_B_fulldata.csv"], "combine_files": True},
    "online_task_equality_processed_1": {"file": "online-1_tsk_equality_processed.csv"},
    "online_task_equality_fulldata_1": {"file": "online-1_tsk_equality_fulldata.csv"},
    "online_task_equality_processed_2": {"file": "online-2_tsk_equality_processed.csv"},
    "online_task_equality_fulldata_2": {"file": "online-2_tsk_equality_fulldata.csv"},
    "online_task_equality_processed_3": {"file": "online-3_tsk_equality_processed.csv"},
    "online_task_equality_fulldata_3": {"file": "online-3_tsk_equality_fulldata.csv"},
    "online_task_metacognition_1": {"file": "online-1_tsk_metacognition.csv"},
    "online_task_metacognition_2": {"file": "online-2_tsk_metacognition.csv"},
    "online_task_metacognition_3": {"file": "online-3_tsk_metacognition.csv"},
    "perceived-stress_1": {"file": "qst-post-1_PSS.csv"},
    "perceived-stress_2": {"file": "qst-post-2_PSS.csv"},
    "perceived-stress_3": {"file": "qst-post-3_PSS.csv"},
    "phy_bodycomposition-basic_1": {"file": "lab-1_phy_body-basic.csv"},
    "phy_bodycomposition-basic_2": {"file": "lab-2_phy_body-basic.csv"},
    "phy_bodycomposition-basic_3": {"file": "lab-3_phy_body-basic.csv"},
    "phy_bodycomposition-advanced_1": {"file": "lab-1_phy_body-advanced.csv"},
    "phy_bodycomposition-advanced_2": {"file": "lab-2_phy_body-advanced.csv"},
    "phy_bodycomposition-advanced_3": {"file": "lab-3_phy_body-advanced.csv"},
    "political-efficacy_2": {"file": "qst-post-2_POE.csv"},
    "political-efficacy_3": {"file": "qst-post-3_POE.csv"},
    "political-participation_1": {"file": "qst-post-1_POP.csv"},
    "political-participation_2": {"file": "qst-post-2_POP.csv"},
    "political-participation_3": {"file": "qst-post-3_POP.csv"},
    "populism_1": {"file": "qst-post-1_POL.csv"},
    "populism_2": {"file": "qst-post-2_POL.csv"},
    "populism_3": {"file": "qst-post-3_POL.csv"},
    "state-anxiety_1": {"file": "qst-post-1_STS.csv"},
    "state-anxiety_2": {"file": "qst-post-2_STS.csv"},
    "state-anxiety_3": {"file": "qst-post-3_STS.csv"},
    "social-support_1": {"file": "qst-post-1_MDP.csv"},
    "social-support_2": {"file": "qst-post-2_MDP.csv"},
    "social-support_3": {"file": "qst-post-3_MDP.csv"},
}

standard_keys = {
    "merge": "line-by-line",
    "dataframes": []
}

for column in columns_to_combine:
    for key in standard_keys:
        if key not in columns_to_combine[column]:
            if key == "merge":
                columns_to_combine[column]["merge"] = "line-by-line"
            if key == "dataframes":
                columns_to_combine[column]["dataframes"] = []
