name: Build Application

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest] # macos-12, ubuntu-latest, 
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pyinstaller --onefile --windowed --add-data ".;." --icon "static/logo.ico" app.py
        else
          pyinstaller --onefile --windowed --add-data ".:." --icon "static/logo.ico" app.py
        fi
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-app
        path: dist/*
